[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition.workspace = true
name = "sand"
version.workspace = true

[[bin]]
name = "sand"

[features]
default = []

[dependencies]
tokio = { workspace = true }
tonlib-client = { workspace = true }
